<# if (this.collection.hasSplit) { #>
<span class="tcb-left pr-5 tcb-active-element-breadcrumbs-item tcb-breadcrumb-compact-item click" data-index="compact" data-fn="expand">
	<?php tcb_icon( 'ellipsis-h-light' ); ?>
	<?php tcb_icon( 'chevron-down-regular', false, 'sidebar', 'drop' ); ?>
	<span class="cont"><i></i></span>
	<div class="tcb-compact-nav-list" style="display:none">
		<# this.collection.collapsed.forEach(function(model, index) { #>
		<a href="javascript:void(0)" class="tcb-left click tcb-active-element-breadcrumbs-item-compact" data-index="<#= index #>" data-fn="clicked">
			<span class="tcb-breadcrumb-name"><#= model.get('name') #></span>
		</a>
		<# }) #>
	</div>
</span>
<# } #>
<# this.collection.visible.forEach(function (model) { #>
<span class="tcb-left pr-5<#= ! model.is_last && ! model.disabled ? ' click' : '' #> tcb-active-element-breadcrumbs-item <# if( ! model.is_last ) { #> tcb-active-element-breadcrumbs-item-after<# } #>" data-index="<#= model.index #>" data-fn="clicked">
	<span class="tcb-breadcrumb-name"><#= model.get('name') #></span>
	<span class="cont"><i></i></span>
</span>
<# }) #>
