<div class="cloud-template-item">
	<div class="cloud-item click<#=selected ? ' active' : ''#>" data-id="<#= item.id || 0 #>" data-fn="dom_select">
		<div class="cb-template-wrapper">
			<div class="cb-template-thumbnail lazy-loading">
				<img class="tve-lazy-img" src='<?php echo tve_editor_css(); ?>/images/loading-spinner.gif' data-src="<#= item.thumb #>" data-ratio="<#= parseFloat(parseInt(item.thumb_size ? item.thumb_size.h : 150) / parseInt(item.thumb_size ? item.thumb_size.w : 150)).toFixed(3) #>"/>
			</div>
		</div>
	</div>
</div>