<div class="fr-dynamic-box fr-link-box" style="display:none">
	<div class="fr-inline-shortcode-links-container tcb-hide mb-20">
		<div class="fr-inline-shortcode-message mb-10"><?php echo __( 'This hyperlink is inherited from the Dynamic Text settings. Edit or disable it from the Dynamic text dropdown', 'thrive-cb' ); ?></div>
		<div class="fr-inline-short-icons">
			<div id="fr-arrow" class="mr-10"><?php tcb_icon( 'noun-arrow' ); ?></div>
			<div class="inline-shortcode-icons">
				<div id="fr-db" class="mr-5"><?php tcb_icon( 'database-regular' ); ?></div>
				<div id="fr-chev"><?php tcb_icon( 'caret-down' ); ?></div>
			</div>
		</div>
	</div>
	<div class="fr-dynamic-links-container">
		<div class="fr-action-buttons row between-xs reverse">
			<div class="fr-dynamic-categories w-100">
				<?php echo tcb_template( 'controls/link/dynamic-categories.phtml', null, true, 'backbone' ) ?>
			</div>
			<div class="fr-dynamic-links w-100">
				<?php echo tcb_template( 'controls/link/dynamic-links.phtml', null, true, 'backbone' ) ?>
			</div>
			<div class="fr-dynamic-link-shortcode w-100 pb-10">
				<input type="text" id="fr-dynamic-link-shortcode-input" placeholder="<?php esc_attr_e('Enter shortcode... [ example ]', 'thrive-cb'); ?>">
			</div>

			<div class="fr-checkbox-line fr-link-atts w-100">
				<span class="fr-checkbox"><input name="target" class="fr-link-attr" data-checked="_blank" type="checkbox" id="fr-link-target"><span><?php tcb_icon( 'froala-checkmark' ); ?></span></span><label for="fr-link-target"><?php echo __( 'Open in new tab', 'thrive-cb' ) ?></label>
				<span class="fr-checkbox"><input name="rel" class="fr-link-attr" data-checked="nofollow" type="checkbox" id="fr-link-rel"><span><?php tcb_icon( 'froala-checkmark' ); ?></span></span><label for="fr-link-rel"><?php echo __( 'Nofollow', 'thrive-cb' ) ?></label>
			</div>
			<button class="fr-command fr-submit" role="button" data-cmd="dynamicLinkInsert" href="#" type="button"><?php echo __( 'Insert', 'thrive-cb' ) ?></button>
			<button class="fr-command fr-danger fr-remove fr-hidden" role="button" data-cmd="dynamicLinkRemove" href="#" type="button"><?php echo __( 'Remove', 'thrive-cb' ) ?></button>
		</div>
	</div>
</div>